### ISSUE TITLE
Cannot install from ansible-galaxy

### ISSUE THREAD

**Issue by sylvainmetayer** [sestrella/ansible-role-asdf#1]
Hello

When trying to install role from [ansible-galaxy](https://galaxy.ansible.com/sestrella/ansible-role-asdf) page an error occurs because their is no Github release. Could you please create one so the role can be instaled with ansible-galaxy command ?

```
- downloading role 'ansible_role_asdf', owned by sestrella
- downloading role from https://github.com/sestrella/ansible-role-asdf/archive/v1.0.0.tar.gz
 [ERROR]: failed to download the file: HTTP Error 404: Not Found
[WARNING]: - sestrella.ansible_role_asdf was NOT installed successfully.
```

**Comment by sestrella** [comment]
@sylvainmetayer thank you for getting in touch, I'll like to refine a couple of things before publishing a release, however, in the meantime, I think you could point to a specific commit message:

```yaml
- src: https://github.com/sestrella/ansible-role-asdf
  version: cf15bccbbae4330ef8afe1e05024fd5415092235
```

Reference:
https://galaxy.ansible.com/docs/using/installing.html

**Comment by sylvainmetayer** [comment]
Thanks for the workaround !
